---
title: "How to join"
format: html
---

# How to Join

## 1) Fill out this form

[MacroMar membership application: Click here to join.](https://forms.gle/6rPBR9qcZXUctTRD7)

## 2) Subscribe to the listserv via Email

-   **To:** `listserv@listserv.neu.edu`

-   **Subject:** Leave this blank.

-   **Message Body:** `SUBSCRIBE macromar YourFirstName YourLastName`

After you send this email, you will get a message to complete your subscription:

```         
Your command:
SUBSCRIBE MACROMAR YourFirstName YourLastName
has been received. You must now reply to this message (as explained below) to complete your subscription. The purpose of this confirmation procedure is to make sure that you have indeed requested to be added to the list.

To confirm the execution of your command, simply click on the following link:
<CLICK ON THE LINK>
```

Then you will receive a confirmation that "You are now subscribed to the MACROMAR list".

To send a message to the list, email `macromar@listserv.neu.edu`. You may receive an email to confirm you are human and then another confirmation message that the post was sent.

## Intending to collaborate?

If you intend to collaborate with the project by submitting data either now or sometime in the future, please fill out our [Intent to Contribute a Dataset Form](MacroMar Intent to Contribute a Dataset) for each dataset you would like to contribute. Submitting this form will generate a MacroMar ID for your dataset. Filling out this form will help us gauge progress towards our goal of 5000 genomes from 100 species.

## Apply for a grant or attend a workshop

We have funds to support sequencing, working groups, and travel to workshops, as well as stipends for completing dataset submissions. Check out our [Funding](https://macromarnet.github.io/MacroMar/Funding.html) page for more information.
