---
title: "Statement of Collaboration and Code of Conduct"
format: html
---


The MacroMar Network is dedicated to promoting collaboration, networking, and the exchange of knowledge. We welcome and encourage participation by all individuals, at any career stage, who have a genuine interest in participating in the project. We strive to cultivate a network built on encouragement, acceptance, and mutual respect, thereby engendering a welcoming environment for all. We will further promote inclusion by fostering a focus on belonging in membership, leadership, committees, outreach, public engagement, recruitment, and in all other areas of activity within the network. We define inclusion as the process of increasing the presence, participation, and achievement of all network members, while attending to the diversity of nationalities, career stages, and identities represented across the MacroMar community. 

## Expectations of members

Members of this marine seascape genomics network commit to the highest standards of scientific integrity, ethics, and environmental stewardship.   The goal of our project is to conduct and facilitate open science. All products will eventually be made publicly available to the fullest extent possible. We expect members of the network to share these values, while respecting Indigenous controls, other forms of controlled access, data sharing agreements, data embargos, and the contributions of others. Members are expected to follow the [FAIR](https://www.go-fair.org/fair-principles/) and [CARE](https://www.gida-global.org/careprinciples) principles, respect the Nagoya Protocol on Access and Benefit-Sharing, honor the rights of coastal and Indigenous peoples, and promote collaboration. Research conducted in developing nations or localized territories must actively involve, empower, and resource scientists from those regions. The network enforces a zero-tolerance policy for harassment, discrimination, bullying, or exploitation in the field, the laboratory, and digital workspaces.

Members are prohibited from sharing embargoed, restricted, or controlled data with chatbots or other AI tools that may retain, use, or further distribute the information.

For authorship and reporting guidelines we will refer participants to the [Vancouver Recommendations](http://www.icmje.org/icmje-recommendations.pdf): a set of recommendations for best practice and ethical standards in the conduct and reporting of published research. They recommend that all 4 of the following criteria are required for authorship: (i) Substantial contributions to the conception or design of the work; or the acquisition, analysis, or interpretation of data for the work; AND (ii) drafting the work or revising it critically for important intellectual content; AND (iii) final approval of the version to be published; AND (iv) agreement to be accountable for all aspects of the work in ensuring that questions related to the accuracy or integrity of any part of the work are appropriately investigated and resolved.

We expect members of the network and its working groups to negotiate authorship structures at the onset of a project, with clear agreements on expectations and roles for all authors that include plans if those expectations are not met. We expect authorship should be offered to local collaborators, technicians, and early-career researchers who contribute significantly to the project’s viability.

Members who contribute data to or conduct large-scale syntheses will agree to our Data Sharing and Authorship Agreement, which will outline authorship policies specific to the use of datasets before and after publication, and will mandate eventual data archiving on a public repository except in clearly-defined special cases. We expect that members who request access to the datasets before they are publicly available for synthesis projects will show a history of engagement with the network.

## Special cases

We ask that our members recognize that we live in a unique time, with strong political forces that can potentially dictate who is allowed to participate in this project. We recognize that some participants, or potential participants, may face hurdles in whether they are allowed to collaborate internationally or use specific scientific terms, with serious consequences that could cause them to lose their livelihood. We ask that members practice patience and understanding as we navigate a shifting political landscape, and strive to develop an inclusive environment.

In addition, some data may not be suited for public use, such as the specific geographic locations of rare or endangered species, or data that Indigenous people have authority to control. Our network will develop recommendations for such cases and help researchers follow best practices. We intend for data collected and disseminated through this project to be [“as open as possible, as closed as necessary”](https://rea.ec.europa.eu/open-science_en). We are committed to the [development of new modes of collaboration, engagement, and partnership with Indigenous Peoples for the care and stewardship of past and future heritage collections](https://localcontexts.org/notice/open-to-collaborate/). We see public data archiving and data control by Indigenous peoples and local communities as joint priorities that are not at odds, and these twin goals will be reflected in our Data Sharing and Authorship Agreement.

## Reporting Mechanisms

Violations of this Code of Conduct—including ethical breaches in MacroMar datasets, data misconduct, violation of data sharing agreements or embargoes, failure to recognize individual contributions, or workplace harassment at MacroMar workshops, working groups, or events—should be reported to a member of the [MacroMar Investigator Team](https://macromarnet.github.io/MacroMar/PIs.html).

An Ethics Committee will be formed to investigate all formal complaints impartially. Confirmed violations will result in tiered disciplinary actions, which may include: (i) temporary suspension of access to network data repositories and funding channels, and (ii) permanent revocation of membership and notification sent to the member’s home institution compliance officer.

